service: fifty-flowers
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    JWT_SECRET: taivu

plugins:
  - serverless-offline
  - serverless-offline-watcher

custom:
  serverless-offline-watcher:
    - path:
        - src
        - index.js
        - serverless.yml
      command: echo "app was modified!"

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
